/**
 * Google Cloud Vision API Configuration
 * 
 * This file contains configuration settings for Google Cloud Vision OCR service.
 * Make sure to set up your Google Cloud project and obtain an API key.
 */

export interface GoogleCloudConfig {
  apiKey: string;
  maxResults: number;
  enableDocumentTextDetection: boolean;
  supportedLanguages: { [key: string]: string };
  timeout: number;
  retryAttempts: number;
}

export const GOOGLE_CLOUD_CONFIG: GoogleCloudConfig = {
  // Google Cloud Vision API Key
  // Get this from Google Cloud Console: https://console.cloud.google.com/
  // Make sure to enable the Vision API for your project
  apiKey: process.env.EXPO_PUBLIC_GOOGLE_CLOUD_API_KEY || '',

  // Maximum number of results to return from OCR
  maxResults: 50,

  // Enable document text detection for better OCR on documents
  enableDocumentTextDetection: true,

  // Supported languages for OCR
  // Language codes follow BCP-47 standard
  supportedLanguages: {
    // International Languages
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'zh': 'Chinese (Simplified)',
    'zh-TW': 'Chinese (Traditional)',
    'ar': 'Arabic',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'id': 'Indonesian',
    'ms': 'Malay',
    'tl': 'Filipino',
    'nl': 'Dutch',
    'sv': 'Swedish',
    'da': 'Danish',
    'no': 'Norwegian',
    'fi': 'Finnish',
    'pl': 'Polish',
    'cs': 'Czech',
    'sk': 'Slovak',
    'hu': 'Hungarian',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'hr': 'Croatian',
    'sr': 'Serbian',
    'sl': 'Slovenian',
    'et': 'Estonian',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'uk': 'Ukrainian',
    'be': 'Belarusian',
    'mk': 'Macedonian',
    'sq': 'Albanian',
    'mt': 'Maltese',
    'is': 'Icelandic',
    'ga': 'Irish',
    'cy': 'Welsh',
    'eu': 'Basque',
    'ca': 'Catalan',
    'gl': 'Galician',
    'af': 'Afrikaans',
    'sw': 'Swahili',
    'zu': 'Zulu',
    'xh': 'Xhosa',
    'st': 'Sesotho',
    'tn': 'Setswana',
    'ss': 'Siswati',
    'ts': 'Xitsonga',
    've': 'Tshivenda',
    'nr': 'Ndebele',
    'nso': 'Northern Sotho',
    'he': 'Hebrew',
    'fa': 'Persian',
    'tr': 'Turkish',
    'az': 'Azerbaijani',
    'ka': 'Georgian',
    'hy': 'Armenian',
    'kk': 'Kazakh',
    'ky': 'Kyrgyz',
    'uz': 'Uzbek',
    'tg': 'Tajik',
    'tk': 'Turkmen',
    'mn': 'Mongolian',
    'my': 'Myanmar (Burmese)',
    'km': 'Khmer',
    'lo': 'Lao',
    'si': 'Sinhala',
    'ne': 'Nepali',
    'dv': 'Divehi',
    'ps': 'Pashto',
    'sd': 'Sindhi',
    'ug': 'Uyghur',
    'bo': 'Tibetan',
    'dz': 'Dzongkha',
    'am': 'Amharic',
    'ti': 'Tigrinya',
    'om': 'Oromo',
    'so': 'Somali',
    'rw': 'Kinyarwanda',
    'rn': 'Kirundi',
    'ny': 'Chichewa',
    'mg': 'Malagasy',
    'eo': 'Esperanto',
    'la': 'Latin',
    'jv': 'Javanese',
    'su': 'Sundanese',
    'mad': 'Madurese',
    'ms-Arab': 'Malay (Arabic)',
    'ms-Latn': 'Malay (Latin)',
    'ban': 'Balinese',
    'bug': 'Buginese',
    'bjn': 'Banjar',
    'ace': 'Acehnese',
    'tet': 'Tetum',
    'ch': 'Chamorro',
    'sm': 'Samoan',
    'to': 'Tongan',
    'fj': 'Fijian',
    'haw': 'Hawaiian',
    'mh': 'Marshallese',
    'na': 'Nauru',
    'nr': 'Ndebele',
    'nv': 'Navajo',
    'oj': 'Ojibwe',
    'cr': 'Cree',
    'iu': 'Inuktitut',
    'kl': 'Kalaallisut',
    'se': 'Northern Sami',
    'fo': 'Faroese',
    'kw': 'Cornish',
    'gd': 'Scottish Gaelic',
    'gv': 'Manx',
    'br': 'Breton',
    'co': 'Corsican',
    'sc': 'Sardinian',
    'rm': 'Romansh',
    'fur': 'Friulian',
    'lld': 'Ladin',
    'vec': 'Venetian',
    'lmo': 'Lombard',
    'pms': 'Piedmontese',
    'lij': 'Ligurian',
    'nap': 'Neapolitan',
    'scn': 'Sicilian',
    'sdc': 'Sassarese',
    'sdn': 'Gallurese',
    'rgn': 'Romagnol',
    'egl': 'Emilian',
    'ext': 'Extremaduran',
    'mwl': 'Mirandese',
    'an': 'Aragonese',
    'ast': 'Asturian',
    'roa-tara': 'Tarantino',
    'nrm': 'Norman',
    'wa': 'Walloon',
    'frp': 'Franco-Provençal',
    'oc': 'Occitan',
    'lad': 'Ladino',
    'mdf': 'Moksha',
    'myv': 'Erzya',
    'kv': 'Komi',
    'udm': 'Udmurt',
    'chm': 'Mari',
    'sah': 'Sakha',
    'tyv': 'Tuvan',
    'alt': 'Southern Altai',
    'kjh': 'Khakas',
    'cjs': 'Shor',
    'dlg': 'Dolgan',
    'evn': 'Evenki',
    'eve': 'Even',
    'chg': 'Chagatai',
    'otk': 'Old Turkic',
    'xqa': 'Karakhanid',
    'zkb': 'Khorezmian',
    'pal': 'Middle Persian',
    'xpr': 'Parthian',
    'sog': 'Sogdian',
    'kho': 'Khotanese',
    'ae': 'Avestan',
    'peo': 'Old Persian',
    'elx': 'Elamite',
    'akk': 'Akkadian',
    'sux': 'Sumerian',
    'hit': 'Hittite',
    'xlu': 'Luwian',
    'xlc': 'Lycian',
    'xld': 'Lydian',
    'xcl': 'Classical Armenian',
    'oge': 'Old Georgian',
    'sva': 'Svan',
    'xmf': 'Mingrelian',
    'lzz': 'Laz',
    'ab': 'Abkhazian',
    'ady': 'Adyghe',
    'kbd': 'Kabardian',
    'ub': 'Ubykh',
    'ce': 'Chechen',
    'inh': 'Ingush',
    'bats': 'Batsbi',
    'xco': 'Chorasmian',
    'os': 'Ossetian',
    'ku': 'Kurdish',
    'ckb': 'Central Kurdish',
    'sdh': 'Southern Kurdish',
    'lki': 'Laki',
    'pnb': 'Western Punjabi',
    'skr': 'Saraiki',
    'hnd': 'Southern Hindko',
    'hno': 'Northern Hindko',
    'phl': 'Phalura',
    'scl': 'Shina',
    'ks': 'Kashmiri',
    'doi': 'Dogri',
    'gbm': 'Garhwali',
    'kha': 'Khasi',
    'lus': 'Mizo',
    'mni': 'Manipuri',
    'sat': 'Santali',
    'hoc': 'Ho',
    'mjz': 'Mahali',
    'unr': 'Mundari',
    'kru': 'Kurukh',
    'kha': 'Khasi',
    'grt': 'Garo',
    'rab': 'Camling',
    'lep': 'Lepcha',
    'lif': 'Limbu',
    'rai': 'Rai',
    'new': 'Newari',
    'mai': 'Maithili',
    'bho': 'Bhojpuri',
    'mag': 'Magahi',
    'awa': 'Awadhi',
    'bra': 'Braj',
    'hne': 'Chhattisgarhi',
    'gom': 'Goan Konkani',
    'kok': 'Konkani',
    'tcy': 'Tulu',
    'bpy': 'Bishnupriya',
    'rkt': 'Rangpuri',
    'rhg': 'Rohingya',
    'ccp': 'Chakma',
    'ctg': 'Chittagonian',
    'syl': 'Sylheti',
    'dv': 'Dhivehi',
    'si': 'Sinhala',
    'pi': 'Pali',
    'sa': 'Sanskrit',
    'pkt': 'Prakrit',
    'inc-ash': 'Ashokan Prakrit',
    'pra': 'Prakrit',
    'inc-ohi': 'Old Hindi',
    'inc-ogu': 'Old Gujarati',
    'inc-oma': 'Old Marathi',
    'inc-obn': 'Old Bengali',
    'inc-oor': 'Old Oriya',
    'inc-opa': 'Old Punjabi',
    'inc-osi': 'Old Sindhi',
    'inc-ote': 'Old Telugu',
    'inc-ota': 'Old Tamil',
    'inc-okn': 'Old Kannada',
    'inc-oml': 'Old Malayalam',

    // Indian Languages (Priority)
    'hi': 'Hindi',
    'te': 'Telugu',
    'ta': 'Tamil',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'gu': 'Gujarati',
    'bn': 'Bengali',
    'mr': 'Marathi',
    'pa': 'Punjabi',
    'or': 'Odia',
    'as': 'Assamese',
    'ur': 'Urdu',
  },

  // Request timeout in milliseconds
  timeout: 30000,

  // Number of retry attempts for failed requests
  retryAttempts: 3,
};

// Language priority for Indian languages
export const INDIAN_LANGUAGE_PRIORITY = [
  'hi', 'te', 'ta', 'kn', 'ml', 'gu', 'bn', 'mr', 'pa', 'or', 'as', 'ur'
];

// Common language combinations for better OCR accuracy
export const LANGUAGE_COMBINATIONS = {
  'indian': ['hi', 'en', 'te', 'ta', 'kn', 'ml', 'gu', 'bn', 'mr', 'pa', 'or', 'as', 'ur'],
  'english': ['en'],
  'multilingual': ['en', 'hi', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'zh', 'ar'],
};

export default GOOGLE_CLOUD_CONFIG;